name: Greenplum Client Tests
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run tests on it'
        required: true
        default: 'main'
jobs:
  test-rocky8:
    runs-on: [self-hosted, Linux, X64]
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.branch }}
    # Remove the setup-python step and use system Python directly
    - name: Verify Python Installation
      run: |
        python3 --version
        pip3 --version
    - name: Install Dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install -r requirements.txt
    - name: Run Tests on Rocky 8
      env:
        GPDB_PLATFORM: rocky8
        GPDB_CLIENT_HOST: ${{ secrets.GPDB_CLIENT_HOST }}
        GPDB_CLIENT_USERNAME: ${{ secrets.GPDB_CLIENT_USERNAME }}
        GPDB_CLIENT_PASSWORD: ${{ secrets.GPDB_CLIENT_PASSWORD }}
        GPDB_HOST: ${{ secrets.GPDB_HOST }}
        GPDB_USERNAME: ${{ secrets.GPDB_USERNAME }}
        GPDB_PASSWORD: ${{ secrets.GPDB_PASSWORD }}
        RP_ENDPOINT: ${{ secrets.RP_ENDPOINT }}
        RP_PROJECT: ${{ secrets.RP_PROJECT }}
        RP_API_KEY: ${{ secrets.RP_API_KEY }}
      run: |
        source ~/.bashrc
        python3 -m pytest -xvs --reportportal
